id: P007995
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG1281
  title: ཆེ་ཤོས་སྐུ་ཕྲེང་གསུམ་པ་བློ་བཟང་བྱང་ཆུབ་བསྟན་པའི་སྒྲོན་མེའི་རང་རྣམ་
  author: ''
  volumes:
    c2db37a582614247ad2f766af7fe5378:
      image_group_id: I1KG1283
      title: Volume 1 of blo bzang byang chub bstan pa'i sgron me rang nyid kyi mdzad
        rnam
      volume_number: 1
      total_pages: 780
      base_file: v001.txt
