id: P007995
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG1281
  title: ཆེ་ཤོས་སྐུ་ཕྲེང་གསུམ་པ་བློ་བཟང་བྱང་ཆུབ་བསྟན་པའི་སྒྲོན་མེའི་རང་རྣམ་
  author: ''
  volumes:
    ec91d32195bb443d9d12754ec9693b76:
      image_group_id: I1KG1283
      title: ''
      volume_number: 1
      total_pages: 780
ebook_metadata:
  title: ཆེ་ཤོས་སྐུ་ཕྲེང་གསུམ་པ་བློ་བཟང་བྱང་ཆུབ་བསྟན་པའི་སྒྲོན་མེའི་རང་རྣམ་
  author: ''
  sku: P007995
  cover: cover.jpg
  layers:
  - pagination
