id: opecha:P007995
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG1281
  title: ཆེ་ཤོས་སྐུ་ཕྲེང་གསུམ་པ་བློ་བཟང་བྱང་ཆུབ་བསྟན་པའི་སྒྲོན་མེའི་རང་རྣམ་
  volume:
    c2db37a582614247ad2f766af7fe5378:
      image_group_id: I1KG1283
      title: Volume 1 of blo bzang byang chub bstan pa'i sgron me rang nyid kyi mdzad
        rnam
      volume_number: 1
      total_pages: 780
  author: ''
ebook_metadata:
  title: ཆེ་ཤོས་སྐུ་ཕྲེང་གསུམ་པ་བློ་བཟང་བྱང་ཆུབ་བསྟན་པའི་སྒྲོན་མེའི་རང་རྣམ་
  author: ''
  sku: P007995
  cover: cover.jpg
  layers:
  - pagination
